---

- name: print the all-groups common variable
  debug: msg="the variable all_var1 has value - {{ all_var1 }} "
  tags: osprint

- name: run command hostname on client - NOTE this wont show anything on screen
  command: "/bin/hostname"

- name: display ansible hostname
  debug: msg="ansible_hostname is - {{ ansible_hostname }}"
  tags: osprint

- name: group variables
  debug: msg="group variable - {{ group_var1 }}"
  tags: osprint

- name: included file variables
  #debugger: on_failed
  debug: msg="os variable value - {{ os }}"
  # tag here gives error that the variable os is not known
  #tags: osprint
  #tags:
    #- 'osprint'

- name: run a shell command and list output
  shell: "cat /etc/hosts"
  register: shell_result

- name: list output of previous command
  debug: 
    var: shell_result.stdout_lines

#- name: run from utils role
    #- include_role: 
        #name: util
        #tasks_from: util1.yml
