---

- name: Running base code
  hosts: all
  #debugger: on_failed
  roles:
  - { role: base }

# This is not working properly - seems to start a new play but does not display any output from tasks
#- name: run from utils role
  #hosts: all
  #tasks:
    #- include_role:
        #name: util
        #tasks_from: util1.yml
